### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by asavt7** [evt/golang-code-to-review#1]
Доброго времени суток,  @evt!
Похоже, тут https://github.com/evt/golang-code-to-review/blob/main/internal/storage/storage.go#L30 не хватает вызовов `s.Lock(), defer s.Unlock()`. 
Отсутствие блокировки приводит к  `fatal error: concurrent map writes`

Тест для воспроизведения:
```go
import (
"strconv"
"testing"
)

func TestStore_Remove(t *testing.T) {
	s := NewStore()
	t.Run("concurrent add and rm", func(t *testing.T) {
		go func() {
			for i := 0; i < 100000; i++ {
				_ := s.Save(strconv.Itoa(i%10), i)
			}
		}()
		for i := 0; i < 10000000; i++ {
			s.Remove(strconv.Itoa(i % 10))
		}
	})
}
```

Запуск `go test`  с аргументом `-race ` выводит ```WARNING: DATA RACE```

P.S.
Спасибо Вам за полезный для разработчиков и мотивирующий youtube канал!

**Comment by evt** [comment]
Пожалуйста ) Сейчас нет времени пофиксить. Сделаешь PR - смерджу )
